---
- name: Update package cache
  apt:
    update_cache: yes
  register: apt_update
  retries: 5
  delay: 5
  until: apt_update is success

- name: Upgrade all packages
  apt:
    upgrade: dist
  notify: reboot_if_needed
