---
- name: Set /etc/timezone to Asia/Almaty
  copy:
    content: "Asia/Almaty\n"
    dest: /etc/timezone
    mode: '0644'

- name: Link /etc/localtime to Asia/Almaty
  file:
    src: /usr/share/zoneinfo/Asia/Almaty
    dest: /etc/localtime
    state: link
    force: yes
  notify: reload_timezone
