---
- name: Get current hostname
  command: hostname
  register: current_hostname
  changed_when: false

- name: Replace old hostname with kai.kz in /etc/hosts
  shell: |
    sed -i "s/{{ current_hostname.stdout }}/kai.kz/g" /etc/hosts
  args:
    executable: /bin/bash
